# Generated by Django 5.0.6 on 2024-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('student', 'Student')], default='student', max_length=50, null=True),
        ),
    ]
