# Generated by Django 5.0.6 on 2024-05-23 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_github_remove_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('kode', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('kode', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fakult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('kode', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kafedra')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='specials',
            field=models.ManyToManyField(blank=True, to='users.special'),
        ),
    ]
