# Generated by Django 5.0.6 on 2024-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fakultet_kafedra_special_profile_specials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
